name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@v3.26
        with:
          user: Kirill9m
          token: ${{ secrets.PAT_TOKEN }}
          filename: github-metrics.svg
          committer_token: ${{ secrets.PAT_TOKEN }}
          committer_message: "Update GitHub Metrics SVG"

          base: header, activity, community, repositories, metadata

          plugin_isocalendar: yes 
          plugin_languages: yes 
          plugin_followup: yes 
          plugin_stars: yes 
          plugin_repositories: yes 
          plugin_topics: yes 
          plugin_lines: yes 
          plugin_achievements: yes 
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B 
