name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@v3.26
        with:
          user: Kirill9m
          token: ${{ secrets.PAT_TOKEN }}
          base: github
          filename: github-metrics.svg
          committer_token: ${{ secrets.PAT_TOKEN }}
          committer_message: "Update GitHub Metrics SVG"
